# Cross-compilation toolchain for Renesas RZ/V2H/V2N (aarch64)
# Based on Renesas rzv_ai_sdk toolchain/runtime.cmake

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_SYSTEM_VERSION 1)
set(MERA_DRP_RUNTIME ON)
set(PRODUCT $ENV{PRODUCT})

set(CMAKE_SYSROOT $ENV{SDKTARGETSYSROOT})

set(CROSS_PREFIX "$ENV{OECORE_NATIVE_SYSROOT}/usr/bin/aarch64-poky-linux/aarch64-poky-linux-")
set(CMAKE_C_COMPILER "${CROSS_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${CROSS_PREFIX}g++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
